name: get_smart
description: A package of widgets and utils to make flutter easy and smart.
homepage: https://github.com/asadbaidar/get_smart

version: 0.1.4+9

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencies
  intl: ^0.17.0
  sprintf: ^6.0.0
  dio: ^4.0.6
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.3
  shimmer: ^2.0.0
  dots_indicator: ^2.1.0
  google_fonts: ^3.0.1
  collection: ^1.16.0
  mime_type: ^1.0.0
  path: ^1.8.1
  http_parser: ^4.0.1
  timeago: ^3.2.2
  flutter_svg: ^1.1.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/

  fonts:
    - family:  GetIcons
      fonts:
        - asset: fonts/GetIcons.ttf