name: get_smart
description: A package of widgets and utils to make flutter easy and smart.
homepage: https://github.com/asadbaidar/get_smart

version: 0.1.1+8

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencies
  intl: ^0.17.0
  sprintf: ^6.0.0
  dio: ^4.0.0
  get: ^4.3.8
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.10
  shimmer: ^2.0.0
  dots_indicator: ^2.0.0
  google_fonts: ^2.1.0
  collection: ^1.15.0
  mime_type: ^1.0.0
  path: ^1.8.0
  http_parser: ^4.0.0
  timeago: ^3.1.0
  #auto_size_text: ^3.0.0-nullsafety.0
  #provider: ^4.3.2+3
  #firebase_core: ^0.5.0
  #firebase_crashlytics: ^0.2.1
  #flutter_svg: ^0.19.0
  #hive: ^1.4.4
  #path_provider: ^1.6.14
  #autocomplete_textfield: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # assets:
  #  - assets/icon/
  #  - assets/image/

  # This adds Flutter specific custom fonts to your application
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  #fonts:
  #  - family: AvenirNext
  #    fonts:
  #      - asset: fonts/AvenirNextLTPro-Regular.otf
  #      - asset: fonts/AvenirNextLTPro-Demi.otf
  #        weight: 600
  #      - asset: fonts/AvenirNextLTPro-Bold.otf
  #        weight: 700
  #      - asset: fonts/AvenirNextLTPro-Italic.otf
  #        style: italic
